### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by Mciocca** [Esri/ember-cli-amd#61] opened 2020-11-20 18:41 UTC
Fastboot currently breaks with this plugin. Are there any plans to support it?

It throws the following error when navigating to a page:
```
ctx.require is not defined
```
Demo app here:
https://github.com/Mciocca/arcgis-bug

**Comment by ffaubry** [comment] 2020-11-20 20:05
No plan. 
Do you want to submit a PR?

**Comment by ffaubry** [comment] 2020-11-20 20:07
I can have a look and see if there is anything obvious.
The issue is that to make AMD works, we are renaming Ember require and define. This way they don't conflict with the dojo/requirejs loader require and define functions.

Some parts of Ember are looking for require and define and are hard to change.

**Comment by Mciocca** [comment] 2020-11-20 20:16
@ffaubry 
Thanks for the response. I can take a look as well but I am not very familiar with addon development / ember-cli development. 
It looks like there is a way to exclude the library from within the addon itself:
https://github.com/ember-fastboot/ember-cli-fastboot#appimport-in-an-addons-included-hook

Unfortunately it doesn't seem like I can disable it from loading with our app itself.

**Comment by ffaubry** [comment] 2020-11-21 07:58
ember-cli-amd is incompatible with fastboot for multiple reasons:
- fastboot is relying on node js to execute server side part of the application. In you case you are trying to use a AMD library that is not compatible with Node JS (such as ArcGIS JSAPI). Even if we could find a way to trick fastboot, the AMD libray would never run in Node JS.
- fastboot is making assumption that the two files to load in the virtual machine are the app.js and the vendor.js. The whole point of ember-cli-amd is to transform the default ember registering/loading logic that is using the AMD semantic but that is not asynchronous. Ember decided to use require and define but in a synchronous way. This is why Ember is incompatible with AMD. When using ember-cli-amd, the ember build result is transformed from the non ember AMD semantic to a pure AMD semantic. Fastboot never anticipated such scenario and hardcoded the registering/loading semantic.

The only hope down the road is:
- progress with ember-embroider
- in you case, arcgis jsapi delivered as pure ES6 modules

This will happen, hopefully, in 2021. When this is happening, ember-cli-amd would be obsolete.
You can track progress here: https://github.com/ember-fastboot/ember-cli-fastboot/issues/700

**Comment by ffaubry** [comment] 2020-11-21 07:58
Closing as nothing can be done.

**Closed by ffaubry** 2020-11-21 07:58 UTC
